application: hello-bottle-app-engine
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:

- url: /h/.*
  script: hello.bottle

- url: /query/.*
  script: query.bottle

- url: /p
  static_dir: public
