application: hello-bottle-app-engine
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:

- url: /api/query
  script: query_controller.bottle

- url: /api/entity
  script: entity_controller.bottle
