application: mecsas-dextra
version: ds-api
runtime: python27
api_version: 1
threadsafe: no

handlers:

- url: /public
  static_dir: public

- url: /api/query
  script: src.routers.query_router.bottle
  login: admin

- url: /api/entity
  script: src.routers.entity_router.bottle
  login: admin

- url: /adm
  script: src.routers.main_router.bottle
  login: admin
