application: datastore-console
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:

- url: /public
  static_dir: public

- url: /api/query
  script: src.routers.query_router.bottle
  login: admin
  auth_fail_action: redirect

- url: /api/entity
  script: src.routers.entity_router.bottle
  login: admin
  auth_fail_action: redirect

- url: /adm
  script: src.routers.main_router.bottle
  auth_fail_action: redirect
  login: admin
